service: cncb-azure-${opt:stage}

provider:
  name: azure
  location: ${opt:region}

plugins:
  - serverless-azure-functions

# you can add packaging information here
#package:
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

functions:
  hello:
    handler: handler.hello
    events:
      - http: true
        x-azure-settings:
          authLevel : anonymous
      - http: true
        x-azure-settings:
          direction: out
          name: res

# The following are a few examples of other events you can configure:
#
# events:
#   - queue: YourQueueName
#     x-azure-settings:
#       connection : StorageAppSettingName
#   - blob:
#     x-azure-settings:
#       name: bindingName
#       direction: in
